### PR TITLE
fixed requirements to match what's used

### PR DESCRIPTION
**Pull request by LucaMarconato**
Some imports were not in the requirements and some required packages were not used. Fixing this.

### CODE REVIEW

**Comment by LucaMarconato** [comment]
@melonora I checked locally that the installation, the tests and the docs generation work. I think we can merge.

**Comment by LucaMarconato** [comment]
Actually gonna merge and make a release, not much to review here.

**Comment by psobolewskiPhD** [comment]
Something still looks off to me: `napari-plugin-engine` ?
Looks like this is a npe2 plugin (napari.yaml) to me.

**Comment by melonora** [comment]
you are right @psobolewskiPhD. The hook here was used to make the plugin the default reader for `.zarr` which the user can just do via `preferences/plugins` as far as I understand. Will adjust.

**Comment by LucaMarconato** [comment]
Thanks both, I have made a new release. CC @goanpeca

**Pull request merged**
