### PR TITLE
Move loading data to separate thread to prevent freezing viewer

### PR DESCRIPTION
**Pull request by Czaki**
As long time freezing viewer is something not nice for user. Even with speedup loading of data, it could take multiple seconds for big data. 

This PR moves loading data and creating `Layer` to a separate thread, keeping the viewer responsible during load time. 
It indicates loading using a progress bar above the selection widget.

### CODE REVIEW

**Review by melonora — APPROVED** [review]
Really nice @Czaki, I just had a play with it and for me it works well. @LucaMarconato you want to have a look still before merge?

**Comment by LucaMarconato** [comment]
Thanks for the PR! Which PRs from napari do I need for this? I am trying this out on a stock napari but I can't see any different as opposed to the old behavior (interface stuck, no loading bar). 

It could also be an os specific behavior?

**Comment by LucaMarconato** [comment]
Could you record a GIF showing what the interface should look like please?

**Comment by Czaki** [comment]
If you are using macos ARM machine with numpy<2, there will be no change because of a bug in the build of numpy wheels for this platform and version. 

https://github.com/user-attachments/assets/4c0540a2-8bcf-4a75-899f-adfcf9e22910

**Comment by LucaMarconato** [comment]
I am indeed using an ARM machine with numpy<2. I'll try the PR with the latest numpy and let you know. Btw, last time I tried the `spatialdata` framework with numpy 2 (1 month ago), some dependent libraries did not support it yet https://github.com/scverse/spatialdata/issues/602.

**Comment by Czaki** [comment]
Instead of using numpy>=2 you may install numpy with `pip install numpy==1.26.4 --no-binary numpy` 
I have improved numpy guard to detect only numpy from pypi wheel. 

relevant numpy issue https://github.com/numpy/numpy/issues/21799

**Comment by Czaki** [comment]
This should not be merged before final decison about https://github.com/napari/napari/pull/7146. 
As this PR will allow to enable thread loading on macOS with proper napari version.

**Comment by LucaMarconato** [comment]
Thanks for the info. I have tried using `pip install --force-reinstall numpy==1.26.4 --no-binary numpy` but I still couldn't see the progressbar. I'll wait until a decision is made in the linked `napari` PR and then try again, eventually in clean conda envs and with the desired numpy version. Please ping me when it's time for me to try, thanks!

**Comment by Czaki** [comment]
> I have tried using `pip install --force-reinstall numpy==1.26.4 --no-binary numpy` but I still couldn't see the progressbar

did you fetch last changes in this PR?

**Pull request merged**
